version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    target-branch: "dev"
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "paryx"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore(deps):"