name: Auto-approve dev to main PR
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref == 'dev'
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.PAT_TOKEN }}