name: Auto-approve dev to main PR
   on:
     pull_request:
       branches:
         - main
   
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.head_ref == 'dev' && github.base_ref == 'main'
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.PAT_TOKEN }}